// export const countryLists = [
//   "Afghanistan",
//   "Albania",
//   "Algeria",
//   "Andorra",
//   "Angola",
//   "Anguilla",
//   "Antigua & Barbuda",
//   "Argentina",
//   "Armenia",
//   "Aruba",
//   "Australia",
//   "Austria",
//   "Azerbaijan",
//   "Bahamas",
//   "Bahrain",
//   "Bangladesh",
//   "Barbados",
//   "Belarus",
//   "Belgium",
//   "Belize",
//   "Benin",
//   "Bermuda",
//   "Bhutan",
//   "Bolivia",
//   "Bosnia & Herzegovina",
//   "Botswana",
//   "Brazil",
//   "British Virgin Islands",
//   "Brunei",
//   "Bulgaria",
//   "Burkina Faso",
//   "Burundi",
//   "Cambodia",
//   "Cameroon",
//   "Canada",
//   "Cape Verde",
//   "Cayman Islands",
//   "Chad",
//   "Chile",
//   "China",
//   "Colombia",
//   "Congo",
//   "Cook Islands",
//   "Costa Rica",
//   "Cote D Ivoire",
//   "Croatia",
//   "Cruise Ship",
//   "Cuba",
//   "Cyprus",
//   "Czech Republic",
//   "Denmark",
//   "Djibouti",
//   "Dominica",
//   "Dominican Republic",
//   "Ecuador",
//   "Egypt",
//   "El Salvador",
//   "Equatorial Guinea",
//   "Estonia",
//   "Ethiopia",
//   "Falkland Islands",
//   "Faroe Islands",
//   "Fiji",
//   "Finland",
//   "France",
//   "French Polynesia",
//   "French West Indies",
//   "Gabon",
//   "Gambia",
//   "Georgia",
//   "Germany",
//   "Ghana",
//   "Gibraltar",
//   "Greece",
//   "Greenland",
//   "Grenada",
//   "Guam",
//   "Guatemala",
//   "Guernsey",
//   "Guinea",
//   "Guinea Bissau",
//   "Guyana",
//   "Haiti",
//   "Honduras",
//   "Hong Kong",
//   "Hungary",
//   "Iceland",
//   "India",
//   "Indonesia",
//   "Iran",
//   "Iraq",
//   "Ireland",
//   "Isle of Man",
//   "Israel",
//   "Italy",
//   "Jamaica",
//   "Japan",
//   "Jersey",
//   "Jordan",
//   "Kazakhstan",
//   "Kenya",
//   "Kuwait",
//   "Kyrgyz Republic",
//   "Laos",
//   "Latvia",
//   "Lebanon",
//   "Lesotho",
//   "Liberia",
//   "Libya",
//   "Liechtenstein",
//   "Lithuania",
//   "Luxembourg",
//   "Macau",
//   "Macedonia",
//   "Madagascar",
//   "Malawi",
//   "Malaysia",
//   "Maldives",
//   "Mali",
//   "Malta",
//   "Mauritania",
//   "Mauritius",
//   "Mexico",
//   "Moldova",
//   "Monaco",
//   "Mongolia",
//   "Montenegro",
//   "Montserrat",
//   "Morocco",
//   "Mozambique",
//   "Namibia",
//   "Nepal",
//   "Netherlands",
//   "Netherlands Antilles",
//   "New Caledonia",
//   "New Zealand",
//   "Nicaragua",
//   "Niger",
//   "Nigeria",
//   "Norway",
//   "Oman",
//   "Pakistan",
//   "Palestine",
//   "Panama",
//   "Papua New Guinea",
//   "Paraguay",
//   "Peru",
//   "Philippines",
//   "Poland",
//   "Portugal",
//   "Puerto Rico",
//   "Qatar",
//   "Reunion",
//   "Romania",
//   "Russia",
//   "Rwanda",
//   "Saint Pierre & Miquelon",
//   "Samoa",
//   "San Marino",
//   "Satellite",
//   "Saudi Arabia",
//   "Senegal",
//   "Serbia",
//   "Seychelles",
//   "Sierra Leone",
//   "Singapore",
//   "Slovakia",
//   "Slovenia",
//   "South Africa",
//   "South Korea",
//   "Spain",
//   "Sri Lanka",
//   "St Kitts & Nevis",
//   "St Lucia",
//   "St Vincent",
//   "St. Lucia",
//   "Sudan",
//   "Suriname",
//   "Swaziland",
//   "Sweden",
//   "Switzerland",
//   "Syria",
//   "Taiwan",
//   "Tajikistan",
//   "Tanzania",
//   "Thailand",
//   "Timor L'Este",
//   "Togo",
//   "Tonga",
//   "Trinidad & Tobago",
//   "Tunisia",
//   "Turkey",
//   "Turkmenistan",
//   "Turks & Caicos",
//   "Uganda",
//   "Ukraine",
//   "United Arab Emirates",
//   "United Kingdom",
//   "United States",
//   "United States Minor Outlying Islands",
//   "Uruguay",
//   "Uzbekistan",
//   "Venezuela",
//   "Vietnam",
//   "Virgin Islands (US)",
//   "Yemen",
//   "Zambia",
//   "Zimbabwe",
// ];
export const stateCityPostcodeData = {
  Bangladesh: {
    states: [
      "Dhaka",
      "Chittagong",
      "Khulna",
      "Rajshahi",
      "Barisal",
      "Sylhet",
      "Rangpur",
    ],
    cities: {
      Dhaka: ["Dhaka", "Gazipur", "Manikganj", "Munshiganj", "Narayanganj"],
      Chittagong: [
        "Chittagong",
        "Cox's Bazar",
        "Bandarban",
        "Rangamati",
        "Khagrachhari",
      ],
      Khulna: ["Khulna", "Jessore", "Satkhira", "Bagerhat", "Magura"],
      Rajshahi: [
        "Rajshahi",
        "Naogaon",
        "Natore",
        "Joypurhat",
        "Chapainawabganj",
      ],
      Barisal: ["Barisal", "Bhola", "Patuakhali", "Jhalokati", "Pirojpur"],
      Sylhet: ["Sylhet", "Moulvibazar", "Habiganj", "Sunamganj"],
      Rangpur: [
        "Rangpur",
        "Dinajpur",
        "Thakurgaon",
        "Panchagarh",
        "Nilphamari",
      ],
    },
    postcodes: {
      Dhaka: "1000",
      Gazipur: "1700",
      Manikganj: "1800",
      Munshiganj: "1500",
      Narayanganj: "1400",
      Chittagong: "4000",
      "Cox's Bazar": "4700",
      Bandarban: "4600",
      Rangamati: "4500",
      Khagrachhari: "4400",
      Khulna: "9000",
      Jessore: "7400",
      Satkhira: "9400",
      Bagerhat: "9300",
      Magura: "7600",
      Rajshahi: "6000",
      Naogaon: "6500",
      Natore: "6400",
      Joypurhat: "5900",
      Chapainawabganj: "6300",
      Barisal: "8200",
      Bhola: "8300",
      Patuakhali: "8600",
      Jhalokati: "8400",
      Pirojpur: "8500",
      Sylhet: "3100",
      Moulvibazar: "3200",
      Habiganj: "3300",
      Sunamganj: "3400",
      Rangpur: "5400",
      Dinajpur: "5200",
      Thakurgaon: "5100",
      Panchagarh: "5300",
      Nilphamari: "5301",
    },
  },
  India: {
    states: ["Maharashtra", "Karnataka", "West Bengal"],
    cities: {
      Maharashtra: ["Mumbai", "Pune", "Nagpur", "Nashik", "Aurangabad"],
      Karnataka: ["Bangalore", "Mysore", "Hubli", "Belgaum", "Mangalore"],
      "West Bengal": [
        "Kolkata",
        "Darjeeling",
        "Siliguri",
        "Asansol",
        "Durgapur",
      ],
    },
    postcodes: {
      Mumbai: "400001",
      Pune: "411001",
      Nagpur: "440001",
      Nashik: "422001",
      Aurangabad: "431001",
      Bangalore: "560001",
      Mysore: "570001",
      Hubli: "580001",
      Belgaum: "590001",
      Mangalore: "575001",
      Kolkata: "700001",
      Darjeeling: "734101",
      Siliguri: "734001",
      Asansol: "713301",
      Durgapur: "713201",
    },
  },
  USA: {
    states: ["California", "Texas", "New York"],
    cities: {
      California: [
        "Los Angeles",
        "San Francisco",
        "San Diego",
        "San Jose",
        "Sacramento",
      ],
      Texas: ["Houston", "Austin", "Dallas", "San Antonio", "Fort Worth"],
      "New York": [
        "New York City",
        "Buffalo",
        "Rochester",
        "Syracuse",
        "Albany",
      ],
    },
    postcodes: {
      "Los Angeles": "90001",
      "San Francisco": "94101",
      "San Diego": "92101",
      "San Jose": "95101",
      Sacramento: "95814",
      Houston: "77001",
      Austin: "73301",
      Dallas: "75201",
      "San Antonio": "78201",
      "Fort Worth": "76101",
      "New York City": "10001",
      Buffalo: "14201",
      Rochester: "14601",
      Syracuse: "13201",
      Albany: "12201",
    },
  },
  Nepal: {
    states: ["Bagmati", "Gandaki", "Lumbini"],
    cities: {
      Bagmati: ["Kathmandu", "Bhaktapur", "Lalitpur", "Kirtipur"],
      Gandaki: ["Pokhara", "Gorkha", "Lamjung", "Tanahun"],
      Lumbini: ["Butwal", "Kapilvastu", "Siddharthanagar", "Palpa"],
    },
    postcodes: {
      Kathmandu: "44600",
      Bhaktapur: "44800",
      Lalitpur: "44700",
      Kirtipur: "44619",
      Pokhara: "33700",
      Gorkha: "34000",
      Lamjung: "33600",
      Tanahun: "33900",
      Butwal: "32907",
      Kapilvastu: "32800",
      Siddharthanagar: "32805",
      Palpa: "32700",
    },
  },
};

//!
// export const stateCityPostcodeData = {
//   Bangladesh: {
//     divisions: {
//       Dhaka: {
//         states: ["Dhaka", "Gazipur", "Narayanganj"],
//         cities: {
//           Dhaka: ["Dhaka", "Gulshan", "Mirpur"],
//           Gazipur: ["Gazipur", "Tongi"],
//           Narayanganj: ["Narayanganj", "Siddhirganj"],
//         },
//         postcodes: {
//           Dhaka: "1000",
//           Gulshan: "1212",
//           Mirpur: "1216",
//           Gazipur: "1700",
//           Tongi: "1710",
//           Narayanganj: "1400",
//           Siddhirganj: "1430",
//         },
//       },
//       Chittagong: {
//         states: ["Chittagong", "Cox's Bazar", "Comilla"],
//         cities: {
//           Chittagong: ["Chittagong", "Chandgaon", "Agrabad"],
//           "Cox's Bazar": ["Cox's Bazar", "Teknaf"],
//           Comilla: ["Comilla", "Barura"],
//         },
//         postcodes: {
//           Chittagong: "4000",
//           Chandgaon: "4212",
//           Agrabad: "4100",
//           "Cox's Bazar": "4700",
//           Teknaf: "4760",
//           Comilla: "3500",
//           Barura: "3570",
//         },
//       },
//       Rajshahi: {
//         states: ["Rajshahi", "Natore", "Bogra"],
//         cities: {
//           Rajshahi: ["Rajshahi", "Puthia", "Bagha"],
//           Natore: ["Natore", "Singra"],
//           Bogra: ["Bogra", "Shibganj"],
//         },
//         postcodes: {
//           Rajshahi: "6000",
//           Puthia: "6290",
//           Bagha: "6350",
//           Natore: "6400",
//           Singra: "6470",
//           Bogra: "5800",
//           Shibganj: "5880",
//         },
//       },
//       Khulna: {
//         states: ["Khulna", "Jessore", "Satkhira"],
//         cities: {
//           Khulna: ["Khulna", "Daulatpur", "Rupsha"],
//           Jessore: ["Jessore", "Jhikargacha"],
//           Satkhira: ["Satkhira", "Tala"],
//         },
//         postcodes: {
//           Khulna: "9000",
//           Daulatpur: "9201",
//           Rupsha: "9220",
//           Jessore: "7400",
//           Jhikargacha: "7450",
//           Satkhira: "9400",
//           Tala: "9460",
//         },
//       },
//       Barisal: {
//         states: ["Barisal", "Patuakhali", "Bhola"],
//         cities: {
//           Barisal: ["Barisal", "Babuganj"],
//           Patuakhali: ["Patuakhali", "Bauphal"],
//           Bhola: ["Bhola", "Char Fasson"],
//         },
//         postcodes: {
//           Barisal: "8200",
//           Babuganj: "8240",
//           Patuakhali: "8600",
//           Bauphal: "8640",
//           Bhola: "8300",
//           "Char Fasson": "8340",
//         },
//       },
//       Sylhet: {
//         states: ["Sylhet", "Moulvibazar", "Habiganj"],
//         cities: {
//           Sylhet: ["Sylhet", "Moulvibazar"],
//           Moulvibazar: ["Moulvibazar", "Kulaura"],
//           Habiganj: ["Habiganj", "Baniachang"],
//         },
//         postcodes: {
//           Sylhet: "3100",
//           Moulvibazar: "3200",
//           Kulaura: "3250",
//           Habiganj: "3300",
//           Baniachang: "3370",
//         },
//       },
//       Rangpur: {
//         states: ["Rangpur", "Lalmonirhat", "Kurigram"],
//         cities: {
//           Rangpur: ["Rangpur", "Dinajpur"],
//           Lalmonirhat: ["Lalmonirhat", "Hatibandha"],
//           Kurigram: ["Kurigram", "Rajarhat"],
//         },
//         postcodes: {
//           Rangpur: "5400",
//           Dinajpur: "5200",
//           Lalmonirhat: "5500",
//           Hatibandha: "5550",
//           Kurigram: "5600",
//           Rajarhat: "5650",
//         },
//       },
//     },
//   },
// };
//!
